### ISSUE TITLE
After updating to 2.2.1 from 2.2 Keepass crashes on launch

### ISSUE THREAD

**Issue by vactirio** [iSnackyCracky/KeePassRDP#38]
**Describe the bug**
After updating to 2.2.1 from 2.2 Keepass crashes on launch
After removing KeepassRDP addin to 2.2.1 then Keepass is ok

Follows error:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: String cannot be of zero length.
Parameter name: oldValue
   at System.String.ReplaceInternal(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue)
   at KeePassRDP.KeePassRDPExt.AssignShortcuts()
   at KeePassRDP.KeePassRDPExt.TriggerSystem_RaisingEvent_AppInitPost(Object sender, EcasRaisingEventArgs e)
   at KeePass.Ecas.EcasTriggerSystem.RaiseEventObj(EcasEvent e, EcasPropertyDictionary props)
   at KeePass.Forms.MainForm.OnFormLoad(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at KeePass.Forms.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.56.0.19520
    Win32 Version: 2.56.0.0
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
CrowdStrike.Sensor.ScriptControl
    Assembly Version: 7.11.18110.0
    Win32 Version: 7.11.18110.0
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/CrowdStrike.Sensor.ScriptControl/7.11.18110.0__02b60967b1f68187/CrowdStrike.Sensor.ScriptControl.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
KeePassRDP
    Assembly Version: 2.2.1.0
    Win32 Version: 2.2.1
    CodeBase: file:///C:/Users/kokkinos.MEGA/AppData/Local/KeePass/PluginCache/ibGmGMthDdqC7qGGyxje/KeePassRDP.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
KeePassRDP.resources
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0
    CodeBase: file:///C:/Users/kokkinos.MEGA/AppData/Local/KeePass/PluginCache/ibGmGMthDdqC7qGGyxje/KeePassRDP.resources.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Users/kokkinos.MEGA/AppData/Local/KeePass/PluginCache/ibGmGMthDdqC7qGGyxje/Newtonsoft.Json.DLL
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.56.0.19520
    Win32 Version: 2.56.0.19520
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by vactirio** [comment]
Went back to 2.2 and worked fine.

**Comment by NETertainer** [comment]
Issue with "Overwrite hotkeys". Sorry for that.
Fixed with v2.2.2.

**Comment by vactirio** [comment]
Please don't be sorry.
Thank you very much for your work....
